import turtle

window = turtle.Screen()
andres = turtle.Turtle()
andres.forward(100)
# andres.left(90)
andres.forward(100)
andres.left(90)
a = int(raw_input('ingrese a'))
andres.forward(20)
a = int(raw_input('ingrese a'))
andres.left(90)
andres.forward(100)
andres.left(90)
andres.forward(100)
andres.left(90)
andres.forward(20)
andres.left(90)
andres.forward(100)
a = int(raw_input('ingrese a'))
andres.left(90)
andres.forward(100)
andres.left(90)
andres.forward(20)
a = int(raw_input('ingrese a'))
andres.left(90)
andres.forward(100)
andres.left(90)
andres.forward(100)
andres.left(90)
andres.forward(20)
andres.left(90)

turtle.mainloop()